version: '3.1'

services:
    php:
        build: docker
        volumes:
            - .:/var/www/html
        depends_on:
            - kafka

    zookeeper:
        image: bitnami/zookeeper
        environment:
            - ALLOW_ANONYMOUS_LOGIN=yes

    kafka:
        image: bitnami/kafka
        depends_on:
          - zookeeper
        environment:
            - KAFKA_LISTENERS=PLAINTEXT://:9092
            - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
            - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
            - ALLOW_PLAINTEXT_LISTENER=yes

    documentor:
        image: phpdoc/phpdoc
        volumes:
            - .:/data
